2020-11-18 16:59:57.476 | INFO     | __main__:serve:85 - 启动服务: 192.168.0.103:64878
2020-11-18 16:59:57.480 | INFO     | __main__:serve:88 - 服务注册开始
2020-11-18 16:59:57.486 | INFO     | __main__:serve:95 - 服务注册成功
2020-11-18 17:04:51.186 | ERROR    | grpc._server:_call_behavior:435 - An error has been caught in function '_call_behavior', process 'MainProcess' (80568), thread 'ThreadPoolExecutor-0_0' (71640):
Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001F9CB322DC0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 71640)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001F9CB322AF0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 71640)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 71640)>
    │    │        │    └ (<weakref at 0x000001F9CD4ED2C0; to 'ThreadPoolExecutor' at 0x000001F9CD361F10>, <_queue.SimpleQueue object at 0x000001F9CD37...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 71640)>
    │    └ <function _worker at 0x000001F9CD3728B0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 71640)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000001F9CD3729D0>
    └ <concurrent.futures.thread._WorkItem object at 0x000001F9CD6F3B20>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000001F9CD6F3B20>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x000001F9CD591F90>, <grpc._server._RPCState object at 0x000001F9CD6F3730>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000001F9CD6F3B20>
             │    └ <function _unary_response_in_pool at 0x000001F9CD3B1310>
             └ <concurrent.futures.thread._WorkItem object at 0x000001F9CD6F3B20>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 552, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <order_srv.handler.order.OrderServicer object at 0x000001F9CD38B8B0>>
                        │              │          └ <grpc._server._RPCState object at 0x000001F9CD6F3730>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x000001F9CD591F90>
                        └ <function _call_behavior at 0x000001F9CD3AFEE0>

> File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x000001F9CD6F39D0>
                           │        └ userId: 1
                           │          address: "\345\214\227\344\272\254\345\270\202"
                           │          mobile: "18787878787"
                           │          name: "bobby"
                           │          post: "\350\257\267\345\260\275...
                           └ <bound method OrderServicer.CreateOrder of <order_srv.handler.order.OrderServicer object at 0x000001F9CD38B8B0>>

  File "C:\Users\Administrator\PycharmProjects\mxshop_srvs\order_srv\handler\order.py", line 191, in CreateOrder
    goods_srv_host, goods_srv_port = register.filter_service(f'Service=="{settings.GOODS_SRV_NAME}"')
                                     │        └ <function ConsulRegister.filter_service at 0x000001F9CCACD700>
                                     └ <common.register.consul.ConsulRegister object at 0x000001F9CD6F3E50>

ValueError: not enough values to unpack (expected 2, got 0)
2020-11-18 17:06:37.857 | INFO     | __main__:on_exit:26 - 注销 6eb1e0fa-297c-11eb-89ca-40b0760ebfa7 服务
2020-11-18 17:06:37.860 | INFO     | __main__:on_exit:28 - 注销成功
