2020-11-18 16:47:28.550 | INFO     | __main__:serve:85 - 启动服务: 192.168.0.103:64462
2020-11-18 16:47:28.553 | INFO     | __main__:serve:88 - 服务注册开始
2020-11-18 16:47:28.558 | INFO     | __main__:serve:95 - 服务注册成功
2020-11-18 16:48:42.284 | ERROR    | grpc._server:_call_behavior:435 - An error has been caught in function '_call_behavior', process 'MainProcess' (76044), thread 'ThreadPoolExecutor-0_0' (39060):
Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000024C78A42DC0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 39060)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000024C78A42AF0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 39060)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 39060)>
    │    │        │    └ (<weakref at 0x0000024C7ABFD360; to 'ThreadPoolExecutor' at 0x0000024C7AA72F10>, <_queue.SimpleQueue object at 0x0000024C7AA8...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 39060)>
    │    └ <function _worker at 0x0000024C7AA7C9D0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 39060)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x0000024C7AA7CAF0>
    └ <concurrent.futures.thread._WorkItem object at 0x0000024C7ACA6700>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x0000024C7ACA6700>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x0000024C7AC9FB80>, <grpc._server._RPCState object at 0x0000024C7ACA6790>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x0000024C7ACA6700>
             │    └ <function _unary_response_in_pool at 0x0000024C7AAC13A0>
             └ <concurrent.futures.thread._WorkItem object at 0x0000024C7ACA6700>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 552, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <order_srv.handler.order.OrderServicer object at 0x0000024C7AA9D8B0>>
                        │              │          └ <grpc._server._RPCState object at 0x0000024C7ACA6790>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x0000024C7AC9FB80>
                        └ <function _call_behavior at 0x0000024C7AABFF70>

> File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x0000024C7ACA6730>
                           │        └ userId: 1
                           │          address: "test"
                           │          mobile: "18787878787"
                           │          name: "bobby"
                           │          post: "tewtt"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <order_srv.handler.order.OrderServicer object at 0x0000024C7AA9D8B0>>

  File "C:\Users\Administrator\PycharmProjects\mxshop_srvs\order_srv\handler\order.py", line 218, in CreateOrder
    inv_srv_host, inv_srv_port = register.filter_service(f'Service=="{settings.INVENTORY_SRV_NAME}"')
                                 │        └ <function ConsulRegister.filter_service at 0x0000024C7A1F1790>
                                 └ <common.register.consul.ConsulRegister object at 0x0000024C7ACA6EB0>

ValueError: not enough values to unpack (expected 2, got 0)
2020-11-18 16:49:02.838 | INFO     | __main__:on_exit:26 - 注销 b04cdf65-297a-11eb-a39c-40b0760ebfa7 服务
2020-11-18 16:49:02.843 | INFO     | __main__:on_exit:28 - 注销成功
