2020-09-30 19:36:53.143 | INFO     | __main__:serve:85 - 启动服务: 192.168.1.102:53780
2020-09-30 19:36:53.147 | INFO     | __main__:serve:88 - 服务注册开始
2020-09-30 19:36:53.154 | INFO     | __main__:serve:95 - 服务注册成功
2020-09-30 19:37:09.450 | ERROR    | grpc._server:_call_behavior:435 - An error has been caught in function '_call_behavior', process 'MainProcess' (36760), thread 'ThreadPoolExecutor-0_0' (41932):
Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000023BC4265F70>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 41932)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000023BC4265CA0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 41932)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 41932)>
    │    │        │    └ (<weakref at 0x0000023BC5ADA310; to 'ThreadPoolExecutor' at 0x0000023BC594DFD0>, <_queue.SimpleQueue object at 0x0000023BC595...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 41932)>
    │    └ <function _worker at 0x0000023BC5956E50>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 41932)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x0000023BC5956F70>
    └ <concurrent.futures.thread._WorkItem object at 0x0000023BC59BCA90>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x0000023BC59BCA90>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x0000023BC59A49F0>, <grpc._server._RPCState object at 0x0000023BC59AF790>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x0000023BC59BCA90>
             │    └ <function _unary_response_in_pool at 0x0000023BC599A940>
             └ <concurrent.futures.thread._WorkItem object at 0x0000023BC59BCA90>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 552, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method GoodsServicer.GoodsList of <goods_srv.handler.goods.GoodsServicer object at 0x0000023BC59776D0>>
                        │              │          └ <grpc._server._RPCState object at 0x0000023BC59AF790>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x0000023BC59A49F0>
                        └ <function _call_behavior at 0x0000023BC599A550>

> File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x0000023BC59BC910>
                           │        └ priceMin: 50
                           │          
                           └ <bound method GoodsServicer.GoodsList of <goods_srv.handler.goods.GoodsServicer object at 0x0000023BC59776D0>>

  File "C:\Users\Administrator\PycharmProjects\mxshop_srvs\goods_srv\handler\goods.py", line 90, in GoodsList
    rsp.data.append(self.convert_model_to_message(good))
    │   │           │    │                        └ <Goods: 424>
    │   │           │    └ <function GoodsServicer.convert_model_to_message at 0x0000023BC51D1F70>
    │   │           └ <goods_srv.handler.goods.GoodsServicer object at 0x0000023BC59776D0>
    │   └ <google.protobuf.internal.python_message._FieldProperty object at 0x0000023BC51AECC0>
    └ <class 'goods_pb2.GoodsListResponse'>

AttributeError: '_FieldProperty' object has no attribute 'append'
